input {
  file {
    path => ["/data/auth_synthetic.log"]
    start_position => "beginning"
    mode => "read"
    sincedb_path => "/usr/share/logstash/data/sincedb-auth"
    codec => plain { charset => "UTF-8" }
  }
}
filter {
  grok {
    match => {
      "message" => [
        "%{SYSLOGTIMESTAMP:auth.ts} %{HOSTNAME:host} %{DATA:process}(?:\\[%{POSINT:pid:int}\\])?: %{GREEDYDATA:auth.msg}"
      ]
    }
    overwrite => ["message"]
  }
  date {
    match    => ["auth.ts", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss"]
    target   => "@timestamp"
    timezone => "Europe/London"
  }
  grok {
    match => {
      "auth.msg" => [
        "Failed password for (?<user>\\S+) from %{IP:src_ip} port %{POSINT:src_port:int}",
        "Invalid user (?<user>\\S+) from %{IP:src_ip} port %{POSINT:src_port:int}",
        "Accepted password for (?<user>\\S+) from %{IP:src_ip} port %{POSINT:src_port:int}"
      ]
    }
    tag_on_failure => ["_grok_ssh_failed"]
  }
  mutate {
    add_field => { "event.dataset" => "auth" "event.module" => "linux" }
    rename    => { "auth.msg" => "message" }
    lowercase => ["host"]
  }
}
output {
  elasticsearch {
    hosts => ["http://host.docker.internal:9200"]  # or your ES host
    index => "lab-auth-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
