input {
  file {
    path => ["/nsm/import/auth_synthetic.log"]
    start_position => "beginning"
    sincedb_path => "/dev/null"   # on Windows use => "NUL"
    mode => "read"
  }
}

filter {
  grok {
    match => {
      "message" => [
        "%{SYSLOGTIMESTAMP:auth.ts} %{HOSTNAME:host} %{DATA:process}(?:\\[%{POSINT:pid:int}\\])?: %{GREEDYDATA:auth.msg}"
      ]
    }
  }
  date {
    match => ["auth.ts", "MMM dd HH:mm:ss"]
    timezone => "Europe/London"
  }
  mutate {
    rename => { "auth.msg" => "message" }
    add_field => { "event.dataset" => "auth" }
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "lab-auth-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
